### ISSUE TITLE
plasma-hud fails to start with Plasma 5.21.1

### ISSUE THREAD

**Issue by ephemient** [Zren/plasma-hud#42]
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/plasma-hud/plasma-hud", line 632, in hud
    appmenu_success = try_dbusmenu_interface(wm_class, kde_appmenu_service_name, kde_appmenu_object_path)
  File "/usr/lib/plasma-hud/plasma-hud", line 472, in try_dbusmenu_interface
    init_rofi()
  File "/usr/lib/plasma-hud/plasma-hud", line 313, in init_rofi
    kdeglobals = KdeGlobalsConfig()
  File "/usr/lib/plasma-hud/plasma-hud", line 229, in __init__
    super().__init__(os.path.abspath(os.path.expanduser('~/.config/kdeglobals')))
  File "/usr/lib/plasma-hud/plasma-hud", line 200, in __init__
    self.read(self.filename)
  File "/usr/lib/python3.9/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.9/configparser.py", line 1067, in _read
    raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from '~/.config/kdeglobals' [line 66]: section 'Colors:Header' already exists
```

Probably because `kdeglobals` contains like

```
[Colors:Header]
BackgroundAlternate=239,240,241
BackgroundNormal=222,224,226
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=61,174,233
ForegroundInactive=112,125,138
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=35,38,41
ForegroundPositive=39,174,96
ForegroundVisited=155,89,182

[Colors:Header][Inactive]
BackgroundAlternate=227,229,231
BackgroundNormal=239,240,241
DecorationFocus=61,174,233
DecorationHover=61,174,233
ForegroundActive=61,174,233
ForegroundInactive=112,125,138
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=35,38,41
ForegroundPositive=39,174,96
ForegroundVisited=155,89,182
```

**Comment by Zren** [comment]
PlasmaHUD should still work if it fails to read `~/.config/kdeglobals` as of https://github.com/Zren/plasma-hud/commit/383bf64a79436b6e21e2cbacf449a3906ede7f1d

Wait, that's a `DuplicateSectionError` not a `ParsingError`.

**Comment by Zren** [comment]
I've changed the error handler to catch the base class `configparser.Error` which [isn't publicly exposed](https://github.com/python/cpython/blob/master/Lib/configparser.py#L151). but seems to work.

If this ever breaks... I'll just catch the general python `Exception` instead. Actually, what error is triggered when kdeglobals doesn't exist?
